version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: 
      context: nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s nginx -g "daemon off;"
    networks:
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
